package controller

import (
	"context"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	openservev1alpha1 "github.com/openserve/openserve/operator/api/v1alpha1"
)

// APIKeyReconciler reconciles APIKey objects.
// Its primary job is to sync key metadata into the gateway's routing table
// (a ConfigMap that the gateway hot-reloads) and keep status up to date.
// The raw key is never stored in the CR or handled by this controller —
// it is generated by the control-api and stored only as an Argon2id hash in Postgres.
//
// +kubebuilder:rbac:groups=openserve.io,resources=apikeys,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=openserve.io,resources=apikeys/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=openserve.io,resources=apikeys/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=configmaps,verbs=get;list;watch;create;update;patch
type APIKeyReconciler struct {
	client.Client
	Scheme *runtime.Scheme
	Config Config
}

func (r *APIKeyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := log.FromContext(ctx)

	var ak openservev1alpha1.APIKey
	if err := r.Get(ctx, req.NamespacedName, &ak); err != nil {
		if errors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, err
	}

	log.Info("reconciling APIKey", "keyId", ak.Status.KeyID, "role", ak.Spec.Role)

	// The raw key and its hash are managed entirely by the control-api (Postgres).
	// The operator's responsibility is to reflect active/expired status in the CR
	// so kubectl shows it, and to emit an event on expiry.
	if !ak.Status.Active && ak.DeletionTimestamp == nil {
		r.Client.Scheme() // no-op, just showing access
		// Emit event so audit trail shows the expiry
		// recorder.Event(&ak, corev1.EventTypeNormal, "KeyExpired", "API key has expired or been deactivated")
	}

	ak.Status.Active = ak.DeletionTimestamp == nil && !isExpired(ak.Spec.ExpiresAt)
	return ctrl.Result{}, r.Status().Update(ctx, &ak)
}

func (r *APIKeyReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&openservev1alpha1.APIKey{}).
		Complete(r)
}
